basePath: /api
definitions:
  github_com_arfan21_synapsis_id_internal_model.CustomerLoginRequest:
    properties:
      email:
        type: string
      password:
        maxLength: 20
        minLength: 8
        type: string
    required:
    - email
    - password
    type: object
  github_com_arfan21_synapsis_id_internal_model.CustomerLoginResponse:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      expires_in_refresh_token:
        type: integer
      refresh_token:
        type: string
      token_type:
        type: string
    type: object
  github_com_arfan21_synapsis_id_internal_model.CustomerRefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  github_com_arfan21_synapsis_id_internal_model.CustomerRegisterRequest:
    properties:
      email:
        type: string
      fullname:
        type: string
      password:
        maxLength: 20
        minLength: 8
        type: string
    required:
    - email
    - fullname
    - password
    type: object
  github_com_arfan21_synapsis_id_internal_model.GetCategoryResponse:
    properties:
      id:
        type: string
      string:
        type: string
    type: object
  github_com_arfan21_synapsis_id_internal_model.ProductCreateRequest:
    properties:
      category_id:
        type: string
      customer_id:
        type: string
      name:
        type: string
      price:
        type: string
      stok:
        type: integer
    required:
    - category_id
    - customer_id
    - name
    - price
    - stok
    type: object
  github_com_arfan21_synapsis_id_pkg_pkgutil.ErrValidationResponse:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      errors:
        items: {}
        type: array
      message:
        example: Success
        type: string
      status:
        example: OK
        type: string
    type: object
host: localhost:8888
info:
  contact:
    name: API Support
    url: http://www.synapsis.id
  description: This is a sample server cell for Synapsis ID Test API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Synapsis ID API
  version: "1.0"
paths:
  /api/v1/customer/login:
    post:
      consumes:
      - application/json
      description: Login Customer
      parameters:
      - description: Payload Customer Login Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_synapsis_id_internal_model.CustomerLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_arfan21_synapsis_id_internal_model.CustomerLoginResponse'
              type: object
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
            - properties:
                errors:
                  items:
                    $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
      summary: Login Customer
      tags:
      - Customer
  /api/v1/customer/refresh-token:
    post:
      consumes:
      - application/json
      description: Refresh Token Customer
      parameters:
      - description: Payload Customer Refresh Token Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_synapsis_id_internal_model.CustomerRefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/github_com_arfan21_synapsis_id_internal_model.CustomerLoginResponse'
              type: object
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
            - properties:
                errors:
                  items:
                    $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
      summary: Refresh Token Customer
      tags:
      - Customer
  /api/v1/customer/register:
    post:
      consumes:
      - application/json
      description: Register Customer
      parameters:
      - description: Payload Customer Register Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_synapsis_id_internal_model.CustomerRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
            - properties:
                errors:
                  items:
                    $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
      summary: Register Customer
      tags:
      - Customer
  /api/v1/products:
    post:
      consumes:
      - application/json
      description: Create Product
      parameters:
      - description: Payload Create Product Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_synapsis_id_internal_model.ProductCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
            - properties:
                errors:
                  items:
                    $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
      summary: Create Product
      tags:
      - Product
  /api/v1/products/categories:
    get:
      consumes:
      - application/json
      description: Get Product Categories
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/github_com_arfan21_synapsis_id_internal_model.GetCategoryResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
      summary: Get Product Categories
      tags:
      - Product
swagger: "2.0"
