basePath: /api
host: localhost:8888
info:
  contact:
    name: API Support
    url: http://www.synapsis.id
  description: This is a sample server cell for Synapsis ID Test API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Synapsis ID API
  version: "1.0"
paths: {}
swagger: "2.0"
