basePath: /api
definitions:
  github_com_arfan21_synapsis_id_internal_model.CustomerRegisterRequest:
    properties:
      email:
        type: string
      fullname:
        type: string
      password:
        maxLength: 20
        minLength: 8
        type: string
    required:
    - email
    - fullname
    - password
    type: object
  github_com_arfan21_synapsis_id_pkg_pkgutil.ErrValidationResponse:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse:
    properties:
      code:
        example: 200
        type: integer
      data: {}
      errors:
        items: {}
        type: array
      message:
        example: Success
        type: string
      status:
        example: OK
        type: string
    type: object
host: localhost:8888
info:
  contact:
    name: API Support
    url: http://www.synapsis.id
  description: This is a sample server cell for Synapsis ID Test API.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Synapsis ID API
  version: "1.0"
paths:
  /api/v1/customer/register:
    post:
      consumes:
      - application/json
      description: Register Customer
      parameters:
      - description: Payload Customer Register Request
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/github_com_arfan21_synapsis_id_internal_model.CustomerRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
        "400":
          description: Error validation field
          schema:
            allOf:
            - $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
            - properties:
                errors:
                  items:
                    $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.ErrValidationResponse'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_arfan21_synapsis_id_pkg_pkgutil.HTTPResponse'
      summary: Register Customer
      tags:
      - Customer
swagger: "2.0"
